import type { Product, Store } from "../search-data";

export interface CategoryItem {
  id: string;
  name: string;
  query: string;
  image: string;
}

export const HERO_BANNER = {
  title: "Meet Our Summer Superheroes",
  subtitle: "Discover fresh collections and seasonal favorites from local Kathmandu shops.",
  image: "/figma/home/hero-banner.png",
  link: "/search",
};

export const PROMO_BANNERS = [
  {
    id: "promo-1",
    title: "Smart Learning",
    image: "/figma/home/promo-banner-1.png",
    link: "/search?category=Education+%26+Training",
  },
  {
    id: "promo-2",
    title: "ShopeeFood / 20.03",
    image: "/figma/home/promo-banner-2.png",
    link: "/search?category=Food+%26+Beverage",
  },
  {
    id: "promo-3",
    title: "Neighborhood Finds",
    image: "/figma/home/promo-banner-3.png",
    link: "/search",
  },
  {
    id: "promo-4",
    title: "Handpicked Deals",
    image: "/figma/home/promo-banner-1.png",
    link: "/search?category=Retail+%26+E-commerce",
  },
];

export const POPULAR_CATEGORIES: CategoryItem[] = [
  { id: "c1", name: "Renewable Energy", query: "Renewable Energy", image: "/figma/home/category-sample.png" },
  { id: "c2", name: "Urban Development", query: "Urban Development", image: "/figma/home/category-sample.png" },
  { id: "c3", name: "Healthcare & Wellness", query: "Healthcare & Wellness", image: "/figma/home/category-sample.png" },
  { id: "c4", name: "Education & Training", query: "Education & Training", image: "/figma/home/category-sample.png" },
  { id: "c5", name: "Technology & Innovation", query: "Technology & Innovation", image: "/figma/home/category-sample.png" },
  { id: "c6", name: "Transportation & Logistics", query: "Transportation & Logistics", image: "/figma/home/category-sample.png" },
  { id: "c7", name: "Environmental Conservation", query: "Environmental Conservation", image: "/figma/home/category-sample.png" },
  { id: "c8", name: "Finance & Banking", query: "Finance & Banking", image: "/figma/home/category-sample.png" },
  { id: "c9", name: "Healthcare & Pharmaceuticals", query: "Healthcare & Pharmaceuticals", image: "/figma/home/category-sample.png" },
  { id: "c10", name: "Technology & Software", query: "Technology & Software", image: "/figma/home/category-sample.png" },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "fp-1",
    name: "Wireless Bluetooth Headphones",
    price: 500,
    originalPrice: 999,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s1",
    storeName: "Audio World Nepal",
    location: "Durbar Marg",
    distance: "1.6 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "fp-2",
    name: "Thermal Paper 58 mm (Pack of 10)",
    price: 500,
    originalPrice: 650,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s6",
    storeName: "Himalayan Bazzar",
    location: "New Baneshwor",
    distance: "1.6 KM",
    inStock: true,
    category: "Office Supplies",
  },
  {
    id: "fp-3",
    name: "Wireless Earbuds Pro with Case",
    price: 2499,
    originalPrice: 3299,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s2",
    storeName: "Sound Haven",
    location: "Putalisadak",
    distance: "2.3 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "fp-4",
    name: "Fast-Charging Power Bank 20000mAh",
    price: 1899,
    originalPrice: 2499,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s5",
    storeName: "Kathmandu Electronics",
    location: "New Baneshwor",
    distance: "1.5 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "fp-5",
    name: "Ergonomic Desk Wireless Mouse",
    price: 850,
    originalPrice: 1200,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s1",
    storeName: "Audio World Nepal",
    location: "Durbar Marg",
    distance: "1.6 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
];

export const FEATURED_STORES: Store[] = [
  {
    id: "s6",
    name: "Himalayan Bazzar",
    verified: true,
    category: "Grocery & Office Supplies",
    location: "New Baneshwor",
    distance: "1.6 KM",
    status: "open",
    rating: 5.0,
    reviewCount: 32,
    cover: "/figma/results/store-imgImage1.png",
    logo: "/figma/results/store-imgAvatarImage1.png",
  },
  {
    id: "s1",
    name: "Audio World Nepal",
    verified: true,
    category: "Audio & Music Equipment",
    location: "Durbar Marg",
    distance: "1.6 KM",
    status: "open",
    rating: 4.8,
    reviewCount: 24,
    cover: "/figma/results/store-imgImage2.png",
    logo: "/figma/results/store-imgAvatarImage2.png",
  },
  {
    id: "s7",
    name: "Paper & Print Nepal",
    verified: true,
    category: "Office Supplies",
    location: "Putalisadak",
    distance: "2.3 KM",
    status: "open",
    rating: 4.8,
    reviewCount: 48,
    cover: "/figma/results/store-imgImage1.png",
    logo: "/figma/results/store-imgAvatarImage2.png",
  },
  {
    id: "s8",
    name: "Kathmandu Stationery",
    verified: false,
    category: "Stationery & Paper",
    location: "Koteshwor",
    distance: "0.8 KM",
    status: "closed",
    rating: 4.6,
    reviewCount: 19,
    cover: "/figma/results/store-imgImage2.png",
    logo: "/figma/results/store-imgAvatarImage1.png",
  },
  {
    id: "s9",
    name: "Office Essentials",
    verified: true,
    category: "Office Supplies",
    location: "Lalitpur",
    distance: "3.2 KM",
    status: "open",
    rating: 4.9,
    reviewCount: 67,
    cover: "/figma/results/store-imgImage1.png",
    logo: "/figma/results/store-imgAvatarImage2.png",
  },
  {
    id: "s3",
    name: "Sports Arena",
    verified: true,
    category: "Sports & Fitness",
    location: "Thamel",
    distance: "0.9 KM",
    status: "closed-today",
    rating: 4.9,
    reviewCount: 42,
    cover: "/figma/results/store-imgImage2.png",
    logo: "/figma/results/store-imgAvatarImage1.png",
  },
];

export const ARTS_HANDICRAFTS_PRODUCTS: Product[] = [
  {
    id: "art-1",
    name: "Handmade Nepali Lokta Paper Journal",
    price: 450,
    originalPrice: 600,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s8",
    storeName: "Kathmandu Stationery",
    location: "Koteshwor",
    distance: "0.8 KM",
    inStock: true,
    category: "Arts & Handicrafts",
  },
  {
    id: "art-2",
    name: "Singing Bowl Handmade Brass 4-Inch",
    price: 1650,
    originalPrice: 2200,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s1",
    storeName: "Audio World Nepal",
    location: "Durbar Marg",
    distance: "1.6 KM",
    inStock: true,
    category: "Arts & Handicrafts",
  },
  {
    id: "art-3",
    name: "Mithila Painting Wooden Wall Clock",
    price: 1250,
    originalPrice: 1500,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s7",
    storeName: "Paper & Print Nepal",
    location: "Putalisadak",
    distance: "2.3 KM",
    inStock: true,
    category: "Arts & Handicrafts",
  },
  {
    id: "art-4",
    name: "Handcrafted Hemp Laptop Sleeve",
    price: 950,
    originalPrice: 1300,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s6",
    storeName: "Himalayan Bazzar",
    location: "New Baneshwor",
    distance: "1.6 KM",
    inStock: true,
    category: "Arts & Handicrafts",
  },
  {
    id: "art-5",
    name: "Pashmina Blend Soft Winter Scarf",
    price: 1800,
    originalPrice: 2500,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s9",
    storeName: "Office Essentials",
    location: "Lalitpur",
    distance: "3.2 KM",
    inStock: true,
    category: "Arts & Handicrafts",
  },
];

export const ELECTRONICS_PRODUCTS: Product[] = [
  {
    id: "elec-1",
    name: "Wireless Bluetooth Headphones",
    price: 500,
    originalPrice: 999,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s1",
    storeName: "Audio World Nepal",
    location: "Durbar Marg",
    distance: "1.6 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "elec-2",
    name: "Multi-Port 65W GaN Fast Charger",
    price: 1499,
    originalPrice: 1999,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s5",
    storeName: "Kathmandu Electronics",
    location: "New Baneshwor",
    distance: "1.5 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "elec-3",
    name: "Smart RGB LED Desk Lamp",
    price: 1100,
    originalPrice: 1600,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s2",
    storeName: "Sound Haven",
    location: "Putalisadak",
    distance: "2.3 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "elec-4",
    name: "Bluetooth Wireless Speaker Mini",
    price: 899,
    originalPrice: 1299,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s1",
    storeName: "Audio World Nepal",
    location: "Durbar Marg",
    distance: "1.6 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
  {
    id: "elec-5",
    name: "Type-C Braided Cable 2M (Pack of 2)",
    price: 399,
    originalPrice: 600,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s5",
    storeName: "Kathmandu Electronics",
    location: "New Baneshwor",
    distance: "1.5 KM",
    inStock: true,
    category: "Electronics & Appliances",
  },
];

export const BEAUTY_COSMETICS_PRODUCTS: Product[] = [
  {
    id: "beauty-1",
    name: "Organic Aloe Vera Hydrating Gel 250ml",
    price: 420,
    originalPrice: 550,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s6",
    storeName: "Himalayan Bazzar",
    location: "New Baneshwor",
    distance: "1.6 KM",
    inStock: true,
    category: "Beauty & Cosmetics",
  },
  {
    id: "beauty-2",
    name: "Pure Himalayan Rose Water Mist 100ml",
    price: 350,
    originalPrice: 480,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s4",
    storeName: "Green Basket",
    location: "Kalanki",
    distance: "5.2 KM",
    inStock: true,
    category: "Beauty & Cosmetics",
  },
  {
    id: "beauty-3",
    name: "Natural Herbal Sunscreen SPF 50",
    price: 750,
    originalPrice: 950,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s6",
    storeName: "Himalayan Bazzar",
    location: "New Baneshwor",
    distance: "1.6 KM",
    inStock: true,
    category: "Beauty & Cosmetics",
  },
  {
    id: "beauty-4",
    name: "Ayurvedic Hair Growth Oil 200ml",
    price: 580,
    originalPrice: 750,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s4",
    storeName: "Green Basket",
    location: "Kalanki",
    distance: "5.2 KM",
    inStock: true,
    category: "Beauty & Cosmetics",
  },
  {
    id: "beauty-5",
    name: "Moisturizing Shea Butter Lip Balm",
    price: 180,
    originalPrice: 250,
    image: "/figma/results/product-imgPhoneImage.png",
    storeId: "s6",
    storeName: "Himalayan Bazzar",
    location: "New Baneshwor",
    distance: "1.6 KM",
    inStock: true,
    category: "Beauty & Cosmetics",
  },
];

export const REQUEST_STEPS = [
  {
    id: "step-1",
    title: "Tell Briz what you need",
    description: "Type it, say it, or upload a photo. Add more details to get better offers.",
    image: "/figma/home/step-tell-briz.png",
  },
  {
    id: "step-2",
    title: "Get offers from local sellers",
    description: "Nearby sellers send offers with price, availability, and distance. No calls. No shop-hopping.",
    image: "/figma/home/step-get-offers.png",
  },
  {
    id: "step-3",
    title: "Compare, chat & choose",
    description: "Compare offers, ask questions, view photos, and agree on a price. Then choose how to pay and receive your order.",
    image: "/figma/home/step-compare-chat.png",
  },
];
